__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

### Решение
$det(A - \lambda I) = 0$<br><br>
$\begin{vmatrix}
(-1 - \lambda) & -6\\
2 & (6 - \lambda)
\end{vmatrix} = (-1 - \lambda)(6 - \lambda) + 12 = 0$<br><br>
Из уравнения находим собственные значения $\lambda_1 = 2, \lambda_2 = 3$<br><br>
Найдем собственные вектора:
<br><br>Для $\lambda_1 = 2$<br>
$\begin{pmatrix}
-1 & -6\\
2 & 6
\end{pmatrix} \cdot 
\begin{pmatrix}
x \\
y
\end{pmatrix} = 2
\begin{pmatrix}
x \\
y
\end{pmatrix}$<br><br>
$\begin{cases}
-x - 6y = 2x\\
2x + 6y = 2y
\end{cases}$, 
$\begin{cases}
x = -2y\\
y = y
\end{cases}$<br><br>
Первый собственный вектор в общем виде
$\begin{pmatrix}
-2y \\
y
\end{pmatrix}$<br><br>
Для $\lambda_2 = 3$<br>
$\begin{pmatrix}
-1 & -6\\
2 & 6
\end{pmatrix} \cdot 
\begin{pmatrix}
x \\
y
\end{pmatrix} = 3
\begin{pmatrix}
x \\
y
\end{pmatrix}$<br><br>
$\begin{cases}
-x - 6y = 3x\\
2x + 6y = 3y
\end{cases}$, 
$\begin{cases}
x = -\frac{3}{2}y\\
y = y
\end{cases}$<br><br>
Второй собственный вектор в общем виде 
$\begin{pmatrix}
-1.5y \\
y
\end{pmatrix}$

In [1]:
import numpy as np
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)
w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

 ### Решение

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x\\ 
y
\end{pmatrix} = \lambda
\begin{pmatrix}
x\\ 
y
\end{pmatrix}
$$
 Находим собственные значения $\lambda_1 = \lambda_2 = -1$
$$\begin{cases}
-x = -x, \\
-y = -y
\end{cases}$$
То есть x и y могут быть любыми

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



### Решение
Найдем собственные значения матрицы:
$$\begin{vmatrix}
1-\lambda & 1\\
-1 & 3-\lambda
\end{vmatrix} = (1-\lambda)(3-\lambda) + 1 = 0
$$<br><br>
$$\lambda_1 = \lambda_2 = 2$$<br><br>
$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\
1
\end{pmatrix} = 2
\begin{pmatrix}
1\\
1
\end{pmatrix}$$
$\begin{cases} 
2 = 2\\
2 = 2
\end{cases}$ Значит вектор является собственным

**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

### Решение
Найдем собсвенные значения

In [2]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
v, _ = np.linalg.eig(A)
print(v)

[ 3. -3.  3.]


#### Проверим вектор

In [3]:
vect = np.array([3, -3, -4])
print(f'A * vect = {A.dot(vect)}')
print(f'lambda1 * vect = {v[0] * vect}')
print(f'lambda2 * vect = {v[1] * vect}')
print(f'lambda3 * vect = {v[2] * vect}')

A * vect = [ -9   9 -12]
lambda1 * vect = [  9.  -9. -12.]
lambda2 * vect = [-9.  9. 12.]
lambda3 * vect = [  9.  -9. -12.]


Вектор не является собственным

In [5]:
b = np.array([[1, 1], [-1, 3]])
v, w = np.linalg.eig(A)
w

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])