## Часть 1

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

<b>Ответ</b><br>
а) определены произведения $AB^T$ размер $4\times4$, $A^TB$ размер $2\times2$, $BA^T$ размер $4\times4$, $B^TA$ размер $2\times2$<br>
б) определены $AB$ размер $2\times3$, $B^TA^T$ размер $3\times2$<br>
в) определены $AB$ размер $8\times8$, $BA$ размер $3\times3$, $A^TB^T$ размер $3\times3$, $B^TA^T$ размер $8\times8$<br>
г) определены все варианты произведений: $AB, A^TB, A^TB^T, BA, B^TA, B^TA^T$, размеры во всех случаях $4\times4$ 

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


<b>Ответ</b><br>
$A + B = \begin{pmatrix}
(1 + 4) & (-2 - 1)\\
(3 + 0) & (0 + 5)
\end{pmatrix} = \begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}$<br><br>
$AB = \begin{pmatrix}
(1\cdot4 + (-2)\cdot0) & (1\cdot(-1) + (-2)\cdot5)\\
(3\cdot4 + 0\cdot0) & (3\cdot(-1) + 0\cdot5)
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}$

In [9]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'A:\n {A}', f'B:\n {B}', f'A+B:\n{A+B}\n',f'AB:\n {A @ B}', sep='\n')

A:
 [[ 1 -2]
 [ 3  0]]
B:
 [[ 4 -1]
 [ 0  5]]
A+B:
[[ 5 -3]
 [ 3  5]]

AB:
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

<b>Ответ</b><br>
$3A - 2B +4C = \begin{pmatrix}
(3\cdot1 - 2\cdot0 + 4\cdot2) & (3\cdot7 - 2\cdot5 + 4\cdot(-4))\\
(3\cdot3 - 2\cdot2 + 4\cdot1) & (3\cdot(-6) - 2\cdot(-1) + 4\cdot1)
\end{pmatrix}$ = $\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

<b>Ответ</b><br>
$A^T = \begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$<br><br>
$AA^T = \begin{pmatrix}
(4^2 + 1^2) & (4\cdot5 - 1\cdot2) & (4\cdot2 + 1\cdot3)\\
(5\cdot4 - 2\cdot1) & (5^2 +(-2)^2) & (5\cdot2 - 2\cdot3)\\
(2\cdot4 + 3\cdot1) & (2\cdot5 - 3\cdot2) & (2^2 + 3^3)
\end{pmatrix}$ = $\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4 \\
11 & 4 & 13\end{pmatrix}$<br><br>
$A^TA = \begin{pmatrix}
(4^2 + 5^2 + 2^2) & (4\cdot1 - 5\cdot2 + 3\cdot2)\\
(1\cdot4 - 2\cdot5 + 3\cdot2) & (1^2 + (-2)^2 + 3^2)
\end{pmatrix}$ = $\begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}$<br>


In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A:\n{A}, \n A_transposed:\n{A.T},\nA*A_transposed:\n{A @ A.T},\nA_transposed*A:\n{A.T @ A}')

A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]], 
 A_transposed:
[[ 4  5  2]
 [ 1 -2  3]],
A*A_transposed:
[[17 18 11]
 [18 29  4]
 [11  4 13]],
A_transposed*A:
[[45  0]
 [ 0 14]]


__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [4]:
def matrix_mul(m1, m2):
    m1_shape = len(m1), len(m1[0])
    m2_shape = len(m2), len(m2[0])
    assert m1_shape[1] == m2_shape[0], "Cannot multiply matrices, wrong shapes!"
    result = []
    for i in range(m1_shape[0]):
        row = []
        for j in range(m2_shape[1]):
            elem = 0
            for k in range(m1_shape[1]):
                elem += m1[i][k] * m2[k][j]
            row.append(elem)
        result.append(row)
    return result


A = [[1, -2], [3, 0], [2, 7]]
B = [[4, -1], [0, 5]]
print(f'A:\n {np.array(A)}', f'B:\n {np.array(B)}', f'AB:\n {np.array(matrix_mul(A, B))}', sep='\n')

A:
 [[ 1 -2]
 [ 3  0]
 [ 2  7]]
B:
 [[ 4 -1]
 [ 0  5]]
AB:
 [[  4 -11]
 [ 12  -3]
 [  8  33]]


In [5]:
a = np.array(A)
b = np.array(B)
a.dot(b)

array([[  4, -11],
       [ 12,  -3],
       [  8,  33]])

## Часть 2

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$



<b>Ответ</b><br>
а) $sin^2(x) + cos^2(x) = 1$<br>
б) Матрица треугольная, знаяит $det(A) = 4\cdot5\cdot9 = 180$<br>
б) $det(A) = 0$ т.к. третья строка линейная комбинация перых двух $A_3 = 2\cdot A_2 - A_1$

In [6]:
import numpy as np
A = np.array([[4, 2, 4], [0, 5, 1], [0, 0, 9]])
print(f'б) det(A) = {np.linalg.det(A):.0f}')
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'в) det(A) = {np.linalg.det(A):.0f}')

б) det(A) = 180
в) det(A) = 0


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

<b>Ответ</b><br>
а) $det(A^2) = det(A\cdot A) = det(A)\cdot det(A) = det^2(A) = 16$<br>
б) $det(A^T) = det(A) = 4$<br>
в) $det(2A) = 2det(A) = 8$

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

вырожденная.

<b>Ответ</b><br>
Определитель равен нулю, т.к. первые две строки линейно-зависимы. Вторая строка равна первой, умноженной на -2

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

<b>Ответ</b><br>
а) определитель матрицы равен нулю, так как третья строка равна сумме первых двух. Ранг матрицы 2 <br>
б) определитель всей матрицы равен нулю, так как третья строка равна сумме первых двух. Ранг матрицы 3

In [7]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'A:\n {A}, rank = {np.linalg.matrix_rank(A)}')
print(f'B:\n {B}, rank = {np.linalg.matrix_rank(B)}')

A:
 [[1 2 3]
 [1 1 1]
 [2 3 4]], rank = 2
B:
 [[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]], rank = 3
