1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.
    

In [7]:
import numpy as np

# 1)
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

U, s, VT = np.linalg.svd(A)

D = np.zeros_like(A, dtype='float32')
D[np.diag_indices(min(A.shape))] = s
print(f'матрица A\n{A}')
print(f'матрица U\n{U}')
print(f'матрица D\n{D}')
print(f'матрица V\n{VT.T}')
print(f'проверка \n{U.dot(D).dot(VT)}')

матрица A
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
матрица U
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
матрица D
[[8.824869  0.        0.       ]
 [0.        6.140606  0.       ]
 [0.        0.        2.5327153]
 [0.        0.        0.       ]
 [0.        0.        0.       ]]
матрица V
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
проверка 
[[ 1.00000003e+00  2.00000003e+00  4.44798946e-08]
 [-4.35033063e-08  1.32951395e-07  5.00000004e+00]
 [ 2.99999997e+00 -3.99999994e+00  1.99999988e+00]
 [ 1.00000003e+00  6.00000019e+00  5.00000019e+00]
 [ 1.07778078e-08  1.00000001e+00  2.65902786e-08]]


In [5]:
# 2)

norm_evklid = np.max(s)
norm_fro = np.sqrt((s*s).sum())

print(norm_evklid, norm_fro)

print(np.linalg.norm(A, ord=2), np.linalg.norm(A, ord='fro'))

8.824868854820448 11.045361017187265
8.824868854820442 11.045361017187261
